. Select the desired endpoint from the ‘Endpoint’ menu. Enter values for the properties provided for that endpoint.

. *_Optional:_*  To add additional parameters, press the btn:[Add] button. To remove a parameter, check the corresponding box and press the btn:[Remove] button.

. Enter the  desired ‘JSON Path’.  See https://goessner.net/articles/JsonPath/[JSONPath - XPath for JSON] for information about the JSON Path syntax.
+
****
Example: JSON Path:: Consider the data at https://jsonplaceholder.typicode.com/users.  The JSONPath string
+
 $.[*][?(@.id < 4)]
+
retrieves all fields (because none are specified) from all objects where the `id` field value is less than 4. The JSONPath string
+
 $.[*][?(@.id < 4)].email
+
retrieves just the `email` field from all objects where the `id` field value is less than 4.
****

. *_Optional:_*  Select ‘Expand Arrays’ to expand a record that contains an array into multiple records.
+
****
.Example: Expand Arrays…
[%collapsible]
=====
include::dataworksheet:partial$expandArrays.adoc[]
=====
****

. Press btn:[OK]. This creates a new data block in the Data Worksheet.

. *_Optional:_* Right-click on the data block, and select ‘Properties’ from the context menu. {rightClickOptions} This opens the ‘Table Properties’ panel. In the ‘Name’ field, enter  a name for the data block, and press btn:[OK]. (See xref:dataworksheet:EditDataWorksheet.adoc[] for information about how to rename columns.)
+
include::ROOT:partial$duplicateNames.adoc[]

. Press the {buttonSave} in the toolbar to save the Data Worksheet.

You can now do mashup operations on this data, as described in xref:dataworksheet:PrepareYourData.adoc[], or you can proceed to create Dashboards  based on this Data Worksheet. See xref:viewsheet:VisualizeYourData.adoc[] for information about how to construct a Dashboard.