.Excel-style Date functions
[example]
=====
xref:GeneralScriptFunctions:CALC_monthname.adoc[]:: Obtain the name of the month from a date field.
+
[source,javascript]
CALC.monthname(field['Date'])
+
xref:GeneralScriptFunctions:dateAdd.adoc[]:: Add or subtract a specified number of days, months, or years from a date field.
+
[source,javascript]
dateAdd('m',-1,field['Date'])
// Subtract one month from the value in the date field
+
xref:GeneralScriptFunctions:dateDiff.adoc[]:: Return the difference in days, months, or years between two dates.
+
[source,javascript]
dateDiff('d',field['Date'],CALC.now())
// Return the number of days elapsed from the Date field value until today
+
xref:GeneralScriptFunctions:CALC_now.adoc[]:: Return the current date and time. Often used with a date operator such as dateDiff() or dateAdd().
+
[source,javascript]
dateDiff('d',field['Date'],CALC.now())
// Return the number of days elapsed from the Date field value until today
=====
.Excel-style Math functions
[example]
=====
CALC.round(number, num_digits):: Round a numerical value to a specified number of decimal places.
+
[source,javascript]
CALC.round(field['Total'],2)

CALC.sqrt(number):: Compute the square root of a value.
+
[source,javascript]
CALC.sqrt(field['Total'])
=====

.Excel-style Text functions
[example]
=====
CALC.proper(String):: Convert a string to “proper” case (initial caps):
+
[source,javascript]
CALC.proper(field['Description'])
+
CALC.trim(string):: Remove extra whitespace from a string.
+
[source,javascript]
CALC.trim('   Mary had a   little     lamb.')
// returns “Mary had a little lamb”.

CALC.len(string):: Return the length of a string, including spaces.
+
[source,javascript]
CALC.len(field['Company'])

CALC.concatenate(array):: Concatenate strings.
+
[source,javascript]
CALC.concatenate([field['First_Name'],' ',field['First_Name']]);
// Or use the JavaScript concatenation operator, “+”:
field['First_Name'] + field['First_Name']

CALC.left(string, num_chars):: Return a specified number of characters from the left side of a string:
+
[source,javascript]
CALC.left(field['Category'], 4);
// Return the first four characters of each category name
=====

.Excel-style Logical functions
[example]
=====
CALC.iif(condition, value_if_true, value_if_false):: Test a condition to determine a return value:
+
[source,javascript]
CALC.iif(field['Total']&gt;500,'big sale','small sale')
// Return ”big sale” if Total is greater than $500, otherwise return “small sale”
// Or use the JavaScript ternary operator:
field['Total']>500 ? 'big sale' : 'small sale'

CALC.and(boolean_1, boolean_2, …, boolean_n):: Return “true” if two or more conditions are simultaneously true. Often used together with a conditional operator such as iif.
+
[source,javascript]
CALC.and(field['Total']&gt;200, field['Quantity Purchased']&lt;10)
// Return true if Total is greater than $200 AND Quantity is less than 10
// Or use the JavaScript “and” operator:
(field['Total']&gt;200) &amp;&amp; (field['Quantity Purchased']&lt;10)
=====